# 服务器配置
server:
  port: 8080 # 默认值
  servlet:
    context-path: / # 默认值

# 连接池配置
spring:
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid的其他属性配置 springboot3整合情况下,数据库连接信息必须在Druid属性下!
    druid:
      url: jdbc:mysql://localhost:3306/project_1
      username: root
      password: '073412'
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.leili.pojo # 配置别名
  mapper-locations: classpath:/mapper/*.xml # mapperxml位置
  configuration: # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

jwt:
  secret: landmine-fly
  expire: 1800000 # 30分钟
  absolute-expire: 86400000 # 24小时