# 服务器配置
server:
  port: 8080 # 默认值
  servlet:
    context-path: / # 默认值

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/ssm_db
      username: root
      password: '073412'
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.leili.bean
  global-config:
    db-config:
      # 设置全局逻辑删除配置
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 默认值
      logic-not-delete-value: 0 # 默认值
      # 设置全局逐渐策略
      id-type: auto
      # 设置全局表名前缀
      table-prefix: news_

# jwt配置（自定义配置）
jwt:
  token:
    tokenExpiration: 120 # token有效时间，单位分钟
    tokenSignKey: HohaiUniversity  # token签名秘钥